boot.o: boot.S multiboot.h x86_desc.h types.h
int_handler.o: int_handler.S
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h i8259.h x86_desc.h rtc.h keyboard.h \
  int_handler.h syscall-handler/sys_linkage.h syscall-handler/./syscall.h \
  syscall-handler/./../types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h page.h rtc.h keyboard.h filesys.h \
  syscall-handler/syscall.h syscall-handler/../types.h
keyboard.o: keyboard.c keyboard.h types.h terminal.h lib.h i8259.h idt.h \
  x86_desc.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h
process.o: process.c process.h types.h syscall-handler/syscall.h \
  syscall-handler/../types.h filesys.h lib.h page.h x86_desc.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c keyboard.h types.h terminal.h lib.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h filesys.h \
  rtc.h terminal.h syscall-handler/syscall.h syscall-handler/../types.h \
  process.h
sys_linkage.o: syscall-handler/sys_linkage.S
syscall.o: syscall-handler/syscall.c syscall-handler/syscall.h \
  syscall-handler/../types.h syscall-handler/../x86_desc.h \
  syscall-handler/../types.h syscall-handler/../rtc.h \
  syscall-handler/../terminal.h syscall-handler/../filesys.h \
  syscall-handler/../lib.h syscall-handler/../process.h \
  syscall-handler/../syscall-handler/syscall.h \
  syscall-handler/../filesys.h
