boot.o: boot.S multiboot.h x86_desc.h types.h
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h i8259.h x86_desc.h rtc.h keyboard.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h page.h rtc.h keyboard.h
keyboard.o: keyboard.c keyboard.h terminal.h lib.h types.h i8259.h idt.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c keyboard.h terminal.h lib.h types.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h
